language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - xctool -workspace Postal.xcworkspace -scheme Postal-iOS -sdk iphonesimulator9.3 build
  - xctool -workspace Postal.xcworkspace -scheme Postal-macOS -sdk macosx10.11 build
